TEAM-SAMSION/Backend

- build.gradle
> PET-29 chore : 프로젝트 의존성 정리

- .github/workflows/CD.yml
* CD application.yml 패키지 경로 수정
> PET-41 chore: CD application.yml 패키지 경로 수정

- .github/workflows/CD.yml
> PET-41 chore: CD gradle 권한 부여

- Api-Module/build.gradle
- Auth-Module/JWT/build.gradle
- Auth-Module/auth-adaptor/build.gradle
- Auth-Module/auth-application/build.gradle
- Auth-Module/build.gradle
- Log-Module/build.gradle
- Log-Module/log-aop/build.gradle
- Log-Module/log-webclient/build.gradle
- build.gradle
- 각 모듈의 build.gradle에 중복 의존성을 베이스 build.gradle에서 관리하도록 수정하였습니다.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-44 chore : 서버 의존성 정리

- Api-Module/build.gradle
- Api-Moduel/build.gradle actuator,prometheus 의존성 추가
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-44 chore : actuator, prometheus 의존성 추가

- Log-Module/log-aop/src/main/java/com/petmory/log/aop/LogTrace.java
- Log-Module/log-aop/src/main/java/com/petmory/log/aop/Pointcuts.java
- 로그 수집기 수정 작업
- 하나의 요청에 대한 로그는 모두 동일한 로그 ID를 가지게 수정
- Pointcuts 수정
- 내용을 적어주세요.
> PET-46 로그 수집기 로직 수정

- Auth-Module/auth-adaptor/src/main/java/com/petmory/authmodule/config/security/SecurityConfig.java
- Auth-Module/auth-adaptor/src/main/java/com/petmory/authmodule/config/security/SecurityHandler.java
- Auth-Module/auth-adaptor/src/main/java/com/petmory/authmodule/config/security/filter/JWTEntryPoint.java
- Common-Module/src/main/java/com/petmory/commonmodule/exception/ErrorResponse.java
- (auth-adaptor) 인증 예외 발생 처리 JWTEntryPoint 클래스 추가
- (Common-Module) 에러 코드 반환 ErrorResponse 클래스 추가
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 41 feat : 인증 예외 발생 처리 JWTEntryPoint 클래스 추가

- Auth-Module/auth-application/build.gradle
- Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/dto/Provider.java
- Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/observer/observer/Impl/AppleOAuthObserver.java
- Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/observer/observer/feign/AppleFeignClient.java
- Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/observer/observer/feign/response/Keys.java
- AppleObserver 추가
- AppleFeignClient 추가 
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-68 feat : 애플 로그인 추가

- .github/workflows/CD.yml
- deploy 패키지 이름 .deploy로 수정
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-73 fix : deploy 패키지 이름 .deploy로 수정

- Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/command/handler/impl/KakaoOAuthHandler.java
- WebClient를 통해 유저 정보 받아오는 로직 작성
- WebClient를 통해 토큰 검증 로직 작성
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-75 feat : 카카오 소셜 로그인 추가

- .github/workflows/CD.yml
- .github/workflows/CI.yml
- Gradle CI/CD 수정
- generateRestDocs task랑 build task랑 동시에 진행되게 수정
- 내용을 적어주세요.
> PET-80 chore : Gradle CI/CD 수정

- .github/workflows/CD.yml
- .github/workflows/CI.yml
- Gradle task 도중 index.html 추가 안되는 문제 수정
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-80 chore : CI/CD 수정

- Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/common/consts/AuthConsts.java
- Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/command/OAuthInvoker.java
- Auth-Module/auth-application/src/test/java/com/pawith/auth/application/JWTExtractEmailServiceTest.java
- Auth-Module/auth-application/src/test/java/com/pawith/auth/application/JWTExtractTokenServiceTest.java
- Auth-Module/auth-application/src/test/java/com/pawith/auth/application/JWTVerifyServiceTest.java
- Auth-Module/auth-application/src/test/java/com/pawith/auth/application/OAuthServiceTest.java
- 내용을 적어주세요.
- JWTExtractTokenService 테스트 코드 작성 중 AuthConsts.AUTHENTICATION_TYPE 에 의한 에러가 발생해서 수정
- 내용을 적어주세요.
> PET-79 test : auth-application 테스트 코드 작성

- Log-Module/Log-Aop/src/main/java/com/pawith/log/aop/LogAspect.java
- Log-Module/Log-Aop/src/main/java/com/pawith/log/aop/LogTrace.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-85 refactor : internal error 예외 메세지 저장

- settings.gradle
- Todo - Domain, Application, Presentation 모듈 추가
- User - Presentation 모듈 추가
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-88 feat : Todo, User 관련 모듈 추가

- Auth-Module/Auth-Application/src/main/java/com/pawith/authmodule/application/port/out/command/handler/impl/AppleOAuthHandler.java
- 관련 예외만 처리하는 방식으로 수정 
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 91 AppleOAuthHandler 예외처리 수정 

- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Assign.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Authority.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Category.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/CategoryStatus.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Pet.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Register.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Todo.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/TodoStatus.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/TodoTeam.java
- Domain-Module/Todo-Module/build.gradle
- 각 테이블 마다의 Entity 코드 생성
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 96 Entity 생성 

- Auth-Module/Auth-Domain/src/main/java/com/pawith/jwt/domain/entity/Token.java
- Token 클래스 BaseEntity 상속하도록 수정
- Token -> Token extends BaseEntity
- 내용을 적어주세요.
> PET-94 fix : Token BaseEntity 설정

- .deploy/docker-compose.yml
- .deploy/promtail.yaml
- .github/workflows/CD.yml
- .gitignore
- Api-Module/src/main/resources/logback.xml
- Log-Module/Log-Aop/src/main/java/com/pawith/log/aop/LogAspect.java
- spring 기반 로그 분석기(TEAM-SAMSION:LogAnalyzer)에서 Grafana:Loki(Promtail) 기반으로 변경
- LogBack 설정 추가
- 로그 경로 .gitignore 추가
- LogAnalyzer로 데이터 전송 클래스 비활성화
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 98 chore : 로그 분석기 통합 설정

- Api-Module/src/main/resources/logback.xml
-  logback scan 수정
- scan="true" 제거
- 내용을 적어주세요.
> PET-98 fix : logback scan 수정

- Domain-Module/Todo-Module/Todo-Application/build.gradle
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/CategoryRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/PetRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoTeamRepository.java
- Domain-Module/Todo-Module/Todo-Presentation/build.gradle
- Todo 도메인 Repository 추가
- Todo-Presentation -> Todo-Application -> Todo-Domain gradle 의존성 정의
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 99 feat : Todo 도메인 Repository 추가

- Api-Module/build.gradle
- Api-Module/src/docs/asciidoc/Index.adoc
- Common-Module/src/main/java/com/pawith/commonmodule/exception/Error.java
- Common-Module/src/main/java/com/pawith/commonmodule/slice/SliceResponse.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoTeamSimpleResponse.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamGetUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/UnregisterUseCase.java
- Domain-Module/Todo-Module/Todo-Domain/build.gradle
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Register.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/exception/NotRegisterUserException.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/exception/TodoException.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/exception/TodoTeamNotFoundException.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterDeleteService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoTeamQueryService.java
- Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/RegisterController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java
- Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/usermodule/utils/UserUtils.java
- TodoTeam 조회 및 탈퇴 API 추가
- TodoTeam 조회 및 탈퇴 API 테스트 및 명세 추가
- SliceResponse 추가
- UserUtils 수정
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 99 feat : TodoTeam 조회 및 탈퇴 API 추가

- Api-Module/src/docs/asciidoc/Index.adoc
- Auth-API.adoc 경로 수정
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 103 fix : Auth-API.adoc 경로 수정

- .deploy/docker-compose.yml
- .deploy/nginx/docker-compose.yml
- .deploy/nginx/nginx.conf
- .github/workflows/Nginx-CD.yml
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoTeamSimpleResponse.java
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java
- Nginx docker-compose.yml 추가
- Nginx 배포 CD 추가
- Server docker-compose.yml에 네트워크 추가
- 내용을 적어주세요.
- nginx 참고 : https://node-js.tistory.com/32
> Pet 105 feat : Nginx 설정 추가

- Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
- Todo Team 랜덤 코드 생성 API 명세 추가
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 108 docs : Todo Team 랜덤 코드 생성 API 명세 추가

- Common-Module/src/main/java/com/pawith/commonmodule/exception/Error.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoTeamNameSimpleResponse.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoRateGetUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamGetUseCase.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/exception/TodoNotFoundException.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoQueryService.java
- Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoHomeController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoHomeControllerTest.java
- 홈 화면 들어갈 때 사용할 가장 최근에 가입한 팀 조회 API 개발
- 기존 달성률 조회 API 위에 변경사항에 따라 로직 수정
- 최근에 가입한 팀 조회 API 테스트 코드 작성 및 문서 반영
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 107 달성률 조회 API 수정, 최근에 가입한 팀 조회 API 추가

- Domain-Module/Image-Module/Image-Domain/src/main/java/com/pawith/imagedomain/service/ImageUploadService.java
- Domain-Module/Image-Module/Image-Infrastructure/src/main/java/com/pawith/imageinfrastructure/service/S3ImageUploadServiceImpl.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/request/PetRegisterRequest.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamCreateUseCase.java
- Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java
- (Todo-Module) Todo 팀 생성시 이미지 파일 비동기적으로 처리되도록 수정
- Image 비동기 업로드 스팩 추가
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 112 refactor : Todo 팀 생성시 이미지 파일 비동기적으로 처리되도록 수정

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoHomeResponse.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignQueryService.java
- Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoHomeController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoHomeControllerTest.java
- 할당받은 Todo 조회 API 개발
- API 테스트 작성 및 명세 추가 
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 113 할당받은 Todo 조회 API

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoRateGetUseCase.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/AssignQueryServiceTest.java
- Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java
- 당일 Assign 조회하는 과정에서 시간 처리를 Application Service 쪽이 아닌 Domain Service 쪽에서 처리하도록 수정
- Controller를 페이지 당 말고 엔티티 별로 생성하기 위해 수정 작업 진행
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 115 Controller Entity별로 생성, 시간 처리 Domain Service쪽에서 처리하도록 수정

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoRateGetUseCase.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/AssignQueryServiceTest.java
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
- Domain-Module/User-Module/User-Application/src/test/java/com/pawith/userapplication/service/UserNicknameChangeUseCaseTest.java
- Todo 완료율 리팩터링
- Repository에서 join와 userId, todoTeamId를 이용한 query로 전체 todo와 완료된 todo 받아오는 쿼리 작성 후 적용
- 내용을 적어주세요.
> Pet 117 refactor : Todo 완료율 리팩터링

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/AssignQueryServiceTest.java
- 할당 받은 Todo 조회 쿼리 최적화
- TodoRepository에서 userId와 todoTeamId를 받아 join을 통해 당일 할당 받은 Todo을 반환하도록 수정
- 내용을 적어주세요.
> Pet 116 Todo 조회 쿼리 최적화

- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoRepository.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET 117 refactor : findTodayTodo 쿼리 수정

- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/handler/impl/KakaoOAuthHandler.java
-  Kakao 응답값 받아오는 Inner Class 수정
- Kakao 응답값 받아오는 Inner Class 수정
- 내용을 적어주세요.
> PET-119 fix : Kakao 소셜로그인 응답값 받는 inner class 수정

- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/handler/impl/KakaoOAuthHandler.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoTeamSimpleResponse.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/TodoTeamMapper.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoRateGetUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamCreateUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamGetUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamRegisterUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/UnregisterUseCase.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoTeamRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/CategoryQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/PetSaveService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterSaveService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoTeamQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoTeamSaveService.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/RegisterQueryServiceTest.java
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
- Todo Team 조회 API 성능 개선
- Todo-Module 서비스 클래스 트랜잭션 명시 통일
- 미사용 메소드들 제거
- KakaoOAuthHandler 메소드 접근 제어자 수정
- TodoTeam 조회시 조인으로 한번에 가져오거나 join fetch 이용으로 n+1 문제 해결
- 내용을 적어주세요.
> Pet 120 refactor : Todo Team 조회 API 성능 개선

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/request/TodoCreateRequest.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterListResponse.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterSimpleInfoResponse.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/TodoMapper.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/RegistersGetUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoCreateUseCase.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Todo.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignSaveService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/CategoryQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoSaveService.java
- Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/RegisterController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
- Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/service/UserQueryService.java
- TodoTeam 등록된 사용자 조회 및 Todo 생성 API 추가
- TodoTeam 등록된 사용자 조회 및 Todo 생성 API 테스트 및 명세 추가
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 121 feat : TodoTeam 등록된 사용자 조회 및 Todo 생성 API 추가

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/AssignSimpleInfoResponse.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoListResponse.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoRateCompareResponse.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoSimpleResponse.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoQueryService.java
- Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET 124 투두 리스트 조회 API 추가

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoRateCompareResponse.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoRateGetUseCase.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoQueryService.java
- Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
- 주차 달성률 비교 API 추가
- 주차 달성률 비교 API 테스트 및 명세 추가
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 128 주차 달성률 비교 API 추가

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/TodoTeamMapper.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamCreateUseCase.java
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java
- Pamily 생성시 Pamily 프로필 이미지 같이 받도록 수정
- Pamily 생성시 Pamily 프로필 이미지 같이 받도록 테스트 수정
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 131 refactor : Pamily 생성시 Pamily 프로필 이미지 같이 받도록 수정

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoTeamSearchInfoResponse.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/TodoTeamMapper.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamGetUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamRegisterUseCase.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoTeamQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/TodoTeamQueryServiceTest.java
- Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java
- TodoTeam 코드를 통한 Pamily 조회 API 추가
- TodoTeam 코드를 통한 Pamily 조회 API 테스트 및 명세 추가 
- todoTeamQueryService.findTodoByCode -> todoTeamQueryService.findTodoTeamByCode 메소드 네이밍 변경
- 내용을 적어주세요.
> Pet 130 feat : TodoTeam 코드를 통한 Pamily 조회 API 추가

- Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/TodoRateGetUseCaseTest.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/AssignSaveServiceTest.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/CategoryQueryServiceTest.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/RegisterQueryServiceTest.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/TodoQueryServiceTest.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/TodoSaveServiceTest.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/TodoTeamQueryServiceTest.java
- Todo-Application, Todo-Domain 테스트 코드 작성
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 132 test : Todo-Application, Todo-Domain 테스트 코드 작성

- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/feign/GoogleOAuthFeignClient.java
- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/feign/NaverOAuthFeignClient.java
- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/feign/response/GoogleUserInfo.java
- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/feign/response/NaverUserInfo.java
- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/handler/AuthHandler.java
- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/handler/impl/GoogleOAuthHandler.java
- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/handler/impl/NaverOAuthHandler.java
- Google, Naver 소셜로그인 사용자 정보 요청 방식 feign client로 변경
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 136 refactor : Google, Naver 소셜로그인 사용자 정보 요청 방식 feign client로 변경

- Common-Module/src/testFixtures/java/com/pawith/commonmodule/utils/FixtureMonkeyUtils.java
- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/LogoutUseCase.java
- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/handler/impl/GoogleOAuthHandler.java
- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/impl/LogoutUseCaseImpl.java
- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/utils/TokenExtractUtils.java
- Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/JWTExtractEmailUseCaseImplTest.java
- Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/JWTExtractTokenUseCaseImplTest.java
- Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/JWTVerifyServiceTest.java
- Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/LogoutUseCaseImplTest.java
- Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/OAuthUseCaseImplTest.java
- Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/command/OAuthInvokerTest.java
- Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/command/handler/impl/GoogleOAuthHandlerTest.java
- Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/command/handler/impl/NaverOAuthHandlerTest.java
- Domain-Module/Auth-Module/Auth-Presentation/src/main/java/com/pawith/authpresentation/OAuthController.java
- 소셜로그인 관련 테스트 코드 작성
- OAuthController logout 메소드 파라미터 추가(@RequestHeader 기반 헤더 추출)
- Java 기본 타입 임의 객체 생성 메소드(FixtureMonkeyUtils) 추가
- 로그아웃 메소드 테스트 추가
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 111 test : 소셜로그인 관련 테스트 코드 작성

- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/impl/JWTVerifyUseCaseImpl.java
- Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/JWTVerifyServiceTest.java
- Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/jwt/JWTProvider.java
- Domain-Module/Auth-Module/Auth-Domain/src/test/java/com/pawith/authdomain/jwt/JWTProviderTest.java
- 토큰 검증시 ACCESS TOKEN, REFRESH TOKEN 검증하도록 조건 추가
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 142 fix : 토큰 검증시 ACCESS TOKEN, REFRESH TOKEN 검증하도록 조건 추가

- Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/dto/request/PathHistoryCreateRequest.java
- Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/handler/UserSignUpHandler.java
- Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/mapper/PathHistoryMapper.java
- Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/mapper/UserMapper.java
- Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/service/PathHistoryCreateUseCase.java
- Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/PathHistory.java
- Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/repository/PathHistoryRepository.java
- Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/service/PathHistorySaveService.java
- Domain-Module/User-Module/User-Presentation/src/docs/asciidoc/User-API.adoc
- Domain-Module/User-Module/User-Presentation/src/main/java/com/pawith/userpresentation/UserController.java
- Domain-Module/User-Module/User-Presentation/src/test/java/com/pawith/userpresentation/UserControllerTest.java
- 포잇을 알게된 경로 저장 API 추가 
- 테스트 코드 작성 및 명세 추가 
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 153 feat : 포잇을 알게된 경로 저장 API 추가 

- .gitignore
- Common-Module/src/main/java/com/pawith/commonmodule/event/UserAccountDeleteEvent.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/UserAccountDeleteOnTodoHandler.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Assign.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignDeleteService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterDeleteService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
- Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/service/UserDeleteUseCase.java
- Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/User.java
- Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/service/UserDeleteService.java
- Domain-Module/User-Module/User-Presentation/src/docs/asciidoc/User-API.adoc
- Domain-Module/User-Module/User-Presentation/src/main/java/com/pawith/userpresentation/UserController.java
- Domain-Module/User-Module/User-Presentation/src/test/java/com/pawith/userpresentation/UserControllerTest.java
- 사용자 탈퇴 API 추가
- User,Assign Soft Delete추가
- Register, Assign은 이벤트 기반으로 제거하도록함
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 143 feat : 사용자 탈퇴 API 추가

- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
- RegisterQueryService 조회 메소드들에서 Function 기반에서 Supplier 기반으로 수정
- RegisterQueryService 조회 메소드들에서 Function 기반에서 Supplier 기반으로 수정
- 내용을 적어주세요.
> Pet 157 refactor : RegisterQueryService 조회 메소드들에서 Function 기반에서 Supplier 기반으로 수정

- Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/handler/UserSignUpHandler.java
- Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/mapper/UserMapper.java
- 소셜 로그인시 사용자 기본 프로필 설정 추가
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet-161 refactor : 소셜 로그인시 사용자 기본 프로필 설정 추가

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> refactor : 카테고리 하위 투두 조회 순서 섞이는 문제 수정

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/request/PetRegisterRequest.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/request/TodoTeamCreateRequest.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/PetMapper.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/TodoTeamMapper.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Pet.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/TodoTeam.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/vo/PetSpecies.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java
- 패밀리 생성시 한줄 소개 및 팻(과, 종) 추가
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 145 feat : 패밀리 생성시 한줄 소개 및 팻(과, 종) 추가

- Common-Module/src/main/java/com/pawith/commonmodule/exception/Error.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterManageInfoResponse.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/ChangeRegisterUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/RegistersGetUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/ChangeRegisterUseCaseTest.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/exception/UnchangeableException.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterValidateService.java
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/RegisterController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
- 관리자가 관리자 권한을 넘겨줄 시, 회원으로 권한 변경
- 운영진이 관리자가 있는 상황에서 다른 사람에게 관리자 권한 부여 시 예외 발생 
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 163 feat : 관리자 페이지 권한 수정에서의 검증 추가

- .deploy/docker-compose.yml
- .github/workflows/CD.yml
- Api-Module/src/main/resources/application-auth.yml
- Api-Module/src/main/resources/application-aws.yml
- Api-Module/src/main/resources/application-db.yml
- Api-Module/src/main/resources/application.yml
- Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/entity/Token.java
- 환경 변수 참조 기반 application.yml으로 변경
- Token 엔티티 soft delete 필드명 deleted -> isDeleted 수정
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 154 chore : 환경 변수 참조 기반 application.yml으로 변경

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/request/AuthorityChangeRequest.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/ChangeRegisterUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/ChangeRegisterUseCaseTest.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Register.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterValidateService.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-163 refactor : 관리자 페이지 권한 수정 시 Enum 활용

- Common-Module/src/main/java/com/pawith/commonmodule/exception/Error.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/exception/AssignNotFoundException.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignQueryService.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-165 fix : Assign 조회 수정

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategoryManageInfoResponse.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/CategoryGetUseCase.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/CategoryRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/CategoryQueryService.java
- Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/CategoryController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/CategoryControllerTest.java
- 관리자 페이지에서 사용할 카테고리 조회 API 추가
- 테스트 코드 작성, 명세 반영
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 166 feat : 카테고리 조회 API (관리자 페이지에서 사용) 추가

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/TodoDeleteOnTodoHandler.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/event/TodoDeleteEvent.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoDeleteUseCase.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Todo.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignDeleteService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoDeleteService.java
- Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
- Todo 삭제 API 추가. soft-delete로 구현 
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 167 feat : Todo 삭제 API 추가 

- Common-Module/src/testFixtures/java/com/pawith/commonmodule/utils/FixtureMonkeyUtils.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoNotificationCreateUseCase.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/TodoNotification.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoNotificationRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoNotificationSaveService.java
- Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
- todo 알림 설정 API 추가
- FixtureMokeyUtils에서 자바 기본타입 Long, Integer 조건 추가했습니다.
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 144 feat : todo 알림 설정 API 추가

- .github/workflows/CD.yml
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-173 chore : firebase.json 설정 추가

- .github/workflows/CD.yml
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 173 fix : json 주입방식 수정

- Common-Module/src/main/java/com/pawith/commonmodule/util/DomainFieldUtils.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-177 refactor : 엔티티 필드 수정 메서드 null 처리 추가

- Common-Module/src/main/java/com/pawith/commonmodule/util/DomainFieldUtils.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-177 refactor : 엔티티 필드 수정 메서드 null 값 처리 추가

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/request/PetRegisterRequest.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/PetInfoResponse.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/PetMapper.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/PetControllerTest.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-177 refactor : 펫 생성,조회,수정 DTO 필드 이름 수정

- Common-Module/src/main/java/com/pawith/commonmodule/util/DomainFieldUtils.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoNotificationCreateUseCase.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/TodoNotification.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoNotificationRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoNotificationSaveService.java
- todo 알림 시간 설정이 되어있으면 기존 시간 변경하는 방식으로 로직 수정
- 도메인 필드 검증 유틸클래스에 검증 빌더 클래스 추가
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 190 fix : todo 알림 시간 설정이 되어있으면 기존 시간 변경하는 방식으로 로직 수정

- Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/UserAuthority.java
- Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/service/UserAuthoritySaveService.java
- Domain-Module/User-Module/User-Domain/src/test/java/com/pawith/userdomain/service/UserAuthoritySaveServiceTest.java
- 사용자 권한 저장 방식 수정
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet-191 fix : 사용자 권한 저장 방식 수정

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamGetUseCase.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
- Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java
- 가장 최근에 생성한 TodoTeam 조회 API 추가, 명세 반영
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 189 feat : 가장 최근에 생성한 TodoTeam 조회 API 추가

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/TodoCompletionCheckOnTodoHandler.java
- Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/handler/TodoCompletionCheckOnTodoHandlerTest.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Todo.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignRepository.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 189 refactor : 쿼리 조건 추가, Todo 낙관적 락 추가

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/TodoTeamMapper.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Register.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterValidateService.java
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
- Register에 가입 날짜 칼럼 추가
- TodoTeam 정렬 기준 가입 날짜로 수정 
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 193 refactor : Register에 가입 날짜 칼럼 추가 

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/TodoTeamMapper.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Register.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-193 refactor : 가입한 날짜 LocalDateTime으로 변경

- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Register.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Todo.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoRepository.java
- Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/User.java
- 날짜별 투두 완료율 계산시 사용하는 카운트 쿼리에 카테고리 활성화 여부 추가
- Todo soft delete시 version 조건 추가
- user, register엔티티에 각각 이메일, userId 인덱스 추가
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-195 fix : todo 조회시 카테고리 활성화 반영

- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Register.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-195 fix : Register 엔티티에 userId 인덱스 설정 수정

- Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/handler/UserSignUpHandler.java
- 사용자 기본 프로필 이미지 변경
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-195 fix : 사용자 기본 프로필 이미지 변경

- Domain-Module/Auth-Module/Auth-Presentation/src/docs/asciidoc/Auth-API.adoc
- Domain-Module/Auth-Module/Auth-Presentation/src/main/java/com/pawith/authpresentation/OAuthController.java
- Domain-Module/Auth-Module/Auth-Presentation/src/test/java/com/pawith/authpresentation/OAuthControllerTest.java
- 소셜 로그인 access token 헤더 받도록 수정
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-197 refactor : 소셜 로그인 access token 헤더 받도록 수정

- Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/User.java
- User 엔티티 필드 수정시 메소드 DomainFieldUtils로 수정
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-198 fix : User 엔티티 필드 수정시 메소드 DomainFieldUtils로 수정

- Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/User.java
- User 엔티티 필드 수정시 메소드 DomainFieldUtils build 수정
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-198 fix : User 엔티티 필드 수정시 메소드 DomainFieldUtils build 수정

- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Category.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Pet.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Register.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Todo.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/TodoTeam.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/vo/PetSpecies.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-200 refactor : DomainFieldUtils 사용

- Alarm-Module/src/main/java/com/pawith/alarmmodule/repository/AlarmRepository.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/TodoNotificationHandler.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoNotificationRepository.java
- 알림 쿼리 수정 및 알림 조회시 내림차순으로 하도록 수정
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 201 refactor : 알림 쿼리 수정 및 알림 조회시 내림차순으로 하도록 수정

- .github/workflows/CD-prod.yml
- .github/workflows/Nginx-CD-prod.yml
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-202 fix : CD 수정

- Api-Module/src/main/resources/logback.xml
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-202 refactor : logback 로그 용량 크기 조정

- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterValidateService.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-200 refactor : 서비스 탈퇴 검증 수정

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/CategoryGetUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/CategoryGetUseCaseTest.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Category.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/CategoryRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/CategoryQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/CategoryQueryServiceTest.java
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/CategoryController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/CategoryControllerTest.java
- Category Entity에 활성/비활성 날짜 저장 칼럼 추가
- 투두 화면에서 카테고리 조회 쿼리 수정
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 207 refactor : 투두 화면 카테고리 조회 로직 수정 

- Common-Module/src/main/java/com/pawith/commonmodule/exception/GlobalExceptionHandler.java
- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/impl/ReissueUseCaseImpl.java
- Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/repository/TokenLockRepository.java
- Domain-Module/Auth-Module/Auth-Presentation/src/main/java/com/pawith/authpresentation/common/security/filter/JWTEntryPoint.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoNotificationRepository.java
- 투두 알림 설정 조회시 연관 레코드 삭제 여부 조건 추가
- 네임드락 timeout 시간 100 -> 1000으로 조정
- 토큰 재발급 로직 리팩터링
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 210 fix : 투두 알림 설정 조회시 연관 레코드 삭제 여부 조건 추가

- Common-Module/src/main/java/com/pawith/commonmodule/cache/CacheTemplate.java
- Common-Module/src/main/java/com/pawith/commonmodule/cache/DefaultCacheTemplate.java
- Common-Module/src/main/java/com/pawith/commonmodule/cache/config/CacheConfig.java
- Common-Module/src/main/java/com/pawith/commonmodule/cache/operators/SetOperator.java
- Common-Module/src/main/java/com/pawith/commonmodule/cache/operators/ValueOperator.java
- Common-Module/src/main/java/com/pawith/commonmodule/cache/operators/impl/DefaultSetOperator.java
- Common-Module/src/main/java/com/pawith/commonmodule/cache/operators/impl/DefaultValueOperator.java
- Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/jwt/JWTProvider.java
- Domain-Module/Auth-Module/Auth-Domain/src/test/java/com/pawith/authdomain/jwt/JWTProviderTest.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoTeamCodeManageService.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/TodoTeamCodeManageServiceTest.java
- Log-Module/src/main/java/com/pawith/log/filter/LogThreadIdHandleFilter.java
- 캐시 관련 인터페이스 정의 및 구현
- 기존 ExpiredMap으로 구현되어 있던 부분 캐시 인터페이스로 변경
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 221 feat : 캐시 관련 인터페이스 정의 및 구현

- Common-Module/src/main/java/com/pawith/commonmodule/cache/operators/impl/DefaultSetOperator.java
- Common-Module/src/main/java/com/pawith/commonmodule/cache/operators/impl/DefaultValueOperator.java
- Common-Module/src/main/java/com/pawith/commonmodule/cache/operators/impl/ExpiredStorage.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/TodoCompletionCheckOnTodoHandler.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Assign.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Todo.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
- todo 완료 상태 변경 로직 리팩터링
- 도메인 메소드로 분리해서 래픽터링 
- assign에서 완료 여부 반환 메소드 추가
- todo 완료 여부 변경 메소드 수정, boolean 받아서 수정하도록
- 내용을 적어주세요.
> Pet 231 refactor : todo 완료 상태 변경 로직 리팩터링

- Common-Module/src/main/java/com/pawith/commonmodule/schedule/AbstractBatchSchedulingHandler.java
- Common-Module/src/main/java/com/pawith/commonmodule/schedule/BatchSchedulingHandler.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/IncompleteTodoCountNotificationHandler.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/TodoNotificationHandler.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamCreateUseCase.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterQueryRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoNotificationQueryRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/dao/IncompleteTodoCountInfoDao.java
- Domain-Module/Todo-Module/Todo-Infrastructure/src/main/java/com/pawith/todoinfrastructure/dao/IncompleteTodoCountInfoDaoImpl.java
- Domain-Module/Todo-Module/Todo-Infrastructure/src/main/java/com/pawith/todoinfrastructure/repository/RegisterRepositoryImpl.java
- Domain-Module/Todo-Module/Todo-Infrastructure/src/main/java/com/pawith/todoinfrastructure/repository/TodoNotificationRepositoryImpl.java
- 사용자들에게 미완료 투두 수 알림 보내는 handler 추가
- 알림 보낼때 사용할 BatchSchedulingHandler 인터페이스 및 추상 클래스 추가
- 
- 기존 투두 알림 handler를 BatchSchedulingHandler 구현으로 수정
- 투두 알림 데이터 반환 쿼리에서 slice -> list로 변경
- 내용을 적어주세요.
> Pet 232 feat : 사용자들에게 미완료 투두 수 알림 보내는 handler 추가

- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterValidateService.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/RegisterValidateServiceTest.java
- 패밀리 탈퇴 검증 테스트 로직 추가
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 234 test : 패밀리 탈퇴 검증 테스트 로직 추가

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/CategoryChangeUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/CategoryChangeUseCaseTest.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Category.java
- Category 상태, 이름 수정 UseCase 테스트 코드 작성
- Category 상태 변경 로직 Entity 안에서 하도록 수정 
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 235 Category 수정 UseCase 테스트 코드 작성, 로직 수정 

- Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/CategoryChangeUseCaseTest.java
- Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/ChangeRegisterUseCaseTest.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterQueryRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/AssignQueryServiceTest.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/RegisterQueryServiceTest.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/RegisterValidateServiceTest.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/TodoQueryServiceTest.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/TodoValidateServiceTest.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/utils/RegisterTestFixtureEntityUtils.java
- Domain-Module/Todo-Module/Todo-Infrastructure/src/main/java/com/pawith/todoinfrastructure/repository/RegisterRepositoryImpl.java
- Todo 도메인 계층 테스트 작성
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 234 feat : Todo 도메인 계층 테스트 작성

- Api-Module/src/main/resources/application-auth.yml
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-253 chore : access token 만료시간 임시 조정

- Api-Module/src/main/resources/application-auth.yml
- 내용을 적어주세요.
- 내용을 적어주세요.
- 기존 1일이였던 만료 시간을 1시간으로 줄엿습니다
> PET-253 chore : access token 만료시간 복구

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoValidateResponse.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoDeleteUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoValidationUseCase.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoTeamQueryRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoTeamQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoValidateService.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/TodoValidateServiceTest.java
- Domain-Module/Todo-Module/Todo-Infrastructure/src/main/java/com/pawith/todoinfrastructure/repository/CategoryRepositoryImpl.java
- Domain-Module/Todo-Module/Todo-Infrastructure/src/main/java/com/pawith/todoinfrastructure/repository/TodoTeamRepositoryImpl.java
- Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/CategoryController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
- Todo 삭제&수정 검증 API GET 메서드로 변경, 응답값으로 Boolean 반환하게 수정
- 카테고리 조회 API 버전 통합 
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 255 refactor : 카테고리 조회 API, Todo 삭제&수정 검증 API 변경

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/request/AssignChangeRequest.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/AssignChangeUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/AssignChageUseCaseTest.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignQueryRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignQueryService.java
- Domain-Module/Todo-Module/Todo-Infrastructure/src/main/java/com/pawith/todoinfrastructure/repository/AssignRepositoryImpl.java
- Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
- Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
- Todo 담당자 수정 API 추가, 명세 반영
- Todo 삭제 및 수정 검증 API 문서에 응답값 타입 null로 보이는 문제 해결
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 260 feat : Todo 담당자 수정 API 추가

- Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-260 test : Todo 등록 API 테스트 코드 수정

- Api-Module/build.gradle
- Common-Module/src/main/java/com/pawith/commonmodule/event/ChristmasEvent.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/RegistersGetUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamRegisterUseCase.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoQueryRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterSaveService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoTeamSaveService.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/RegisterSaveServiceTest.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/TodoTeamSaveServiceTest.java
- Domain-Module/Todo-Module/Todo-Infrastructure/src/main/java/com/pawith/todoinfrastructure/repository/TodoRepositoryImpl.java
- Event/build.gradle
- Event/src/main/java/com/pawith/event/christmas/ChristmasEventCloseHandler.java
- Event/src/main/java/com/pawith/event/christmas/ChristmasEventListener.java
- Event/src/main/java/com/pawith/event/christmas/ChristmasEventPublishHandler.java
- Event/src/main/java/com/pawith/event/christmas/ChristmasEventService.java
- Event/src/main/java/com/pawith/event/christmas/entity/ChristmasCategory.java
- Event/src/main/java/com/pawith/event/christmas/repository/ChristmasCategoryRepository.java
- settings.gradle
- 크리스마스 이벤트 로직 추가
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 261 feat : 크리스마스 이벤트 로직 추가

- Event/src/main/java/com/pawith/event/christmas/ChristmasEventCloseHandler.java
- Event/src/main/java/com/pawith/event/christmas/ChristmasEventPublishHandler.java
- Event/src/main/java/com/pawith/event/christmas/ChristmasEventService.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-261 refactor : 이벤트 시작 시간 복구

- Common-Module/src/main/java/com/pawith/commonmodule/domain/BatchInsertRepository.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoCreateUseCase.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Register.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignBatchRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignSaveService.java
- Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/AssignSaveServiceTest.java
- Domain-Module/Todo-Module/Todo-Infrastructure/src/main/java/com/pawith/todoinfrastructure/repository/AssignBatchRepositoryImpl.java
- gradle/spring.gradle
- Todo 생성 로직 Batch Insert로 변경
- Assign 배치 단위로 저장할 수 있는 로직 추가
- Register 엔티티에 userId 일치 여부 조회 메소드 추가
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 277 refactor : Todo 생성 로직 Batch Insert로 변경

- Event/src/main/java/com/pawith/event/christmas/ChristmasEventService.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-278 fix : 크리스마스 이벤트 기간 연장

- Event/src/main/java/com/pawith/event/christmas/ChristmasEventService.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-278 feat : 크리스마스 이벤트 투두 추가 생성 로직 추가

- Common-Module/src/main/java/com/pawith/commonmodule/cache/DefaultCache.java
- Common-Module/src/main/java/com/pawith/commonmodule/cache/DefaultCacheManger.java
- Common-Module/src/main/java/com/pawith/commonmodule/cache/config/CacheConfig.java
- Common-Module/src/main/java/com/pawith/commonmodule/cache/operators/ValueOperator.java
- Common-Module/src/main/java/com/pawith/commonmodule/cache/operators/impl/DefaultValueOperator.java
- ExpiredMap 기반 Cache, CacheManger 구현체 추가
- ValueOperator에 모든 키값 조회 메소드 추가
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 281 feat : ExpiredMap 기반 Cache, CacheManger 구현체 추가

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoTeamInfoResponse.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/TodoCompletionCheckOnTodoHandler.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/event/TodoCompletionCheckEvent.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/TodoTeamMapper.java
- Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/handler/TodoCompletionCheckOnTodoHandlerTest.java
- 패밀리 가입 기간 로직 수정 
- TodoCompletionCheckEvent record로 변경
- Period -> ChronoUnit 사용으로 변경
- 내용을 적어주세요.
> Pet 282 fix : 패밀리 가입 기간 로직 수정

- Alarm-Module/src/main/java/com/pawith/alarmmodule/repository/AlarmBatchRepository.java
- Alarm-Module/src/main/java/com/pawith/alarmmodule/repository/impl/AlarmBatchRepositoryImpl.java
- Alarm-Module/src/main/java/com/pawith/alarmmodule/service/AlarmService.java
- Common-Module/src/main/java/com/pawith/commonmodule/event/UserAccountDeleteEvent.java
- Common-Module/src/main/java/com/pawith/commonmodule/event/UserSignUpEvent.java
- Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/jwt/JWTProvider.java
- Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/jwt/TokenType.java
- Domain-Module/Auth-Module/Auth-Domain/src/test/java/com/pawith/authdomain/jwt/JWTProviderTest.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/UserAccountDeleteOnTodoHandler.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/RegistersGetUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamGetUseCase.java
- Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/TodoGetUseCaseTest.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignQueryService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoTeamCodeManageService.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/util/AssignUtils.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/util/RegisterUtils.java
- Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/handler/UserSignUpHandler.java
- Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/mapper/UserMapper.java
- Domain-Module/User-Module/User-Application/src/test/java/com/pawith/userapplication/handler/UserSignUpHandlerTest.java
- RegisterUtils, AssignUtils 추가
- Register 조회 로직 리팩터링
- 일부 클래스 record로 변경
- JWTProvider 미사용 메소드 제거
- 일부 클래스 불변성 보장을 위한 final 추가
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 285 feat : RegisterUtils, AssignUtils 추가 및 리팩터링

- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/TodoRemindHandler.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/UserAccountDeleteOnTodoHandler.java
- Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignQueryRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/dao/IncompleteAssignInfoDao.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignQueryService.java
- Domain-Module/Todo-Module/Todo-Infrastructure/src/main/java/com/pawith/todoinfrastructure/dao/IncompleteAssignInfoDaoImpl.java
- Domain-Module/Todo-Module/Todo-Infrastructure/src/main/java/com/pawith/todoinfrastructure/repository/AssignRepositoryImpl.java
- 과반수 이상 투두 완료시 알림 생성 로직 리팩터링
- 카운트 쿼리에서 동적 쿼리 사용해서 메소드 countAssignByTodoIdAndCompleteStatus, countAssignByTodoId 2개 만들었습니다. 
- 알림 생성 로직 리팩터링하면서 projection 사용했습니다~
- 내용을 적어주세요.
> Pet 286 refactor : 과반수 이상 투두 완료시 알림 생성 로직 리팩터링

- Api-Module/build.gradle
- Batch-Module/build.gradle
- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/handler/OAuthSuccessHandler.java
- Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/handler/OAuthSuccessHandlerTest.java
- Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/repository/OAuthRepository.java
- Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/service/OAuthQueryService.java
- Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/User.java
- gradle/customplugin/gradleutils.gradle
- gradleutils 정의 및 필요 모듈 정보 반환해주는 메소드 추가
- API 모듈의 도메인 presentation 의존성 자동화
- 배치 모듈 추가 및 도메인 모듈 의존성 자동화
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 303 chore : gradle 의존성 설정 자동화

- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/oauth/feign/response/TokenInfo.java
- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/oauth/impl/AppleOAuthHandler.java
- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/oauth/impl/KakaoOAuthHandler.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoTeamQueryRepository.java
- Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoTeamQueryService.java
- Domain-Module/Todo-Module/Todo-Infrastructure/src/main/java/com/pawith/todoinfrastructure/repository/TodoTeamRepositoryImpl.java
- 애플, 카카오 소셜 로그인 시 회원 정보 식별 id도 같이 받아오도록 추가
- Optional 처리 안되어 있는 부분 수정 
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 304 feat : 소셜 로그인 시 회원 정보 식별 id도 같이 받아오도록 추가

- Domain-Module/Auth-Module/Auth-Application/build.gradle
- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/oauth/impl/AppleOAuthHandler.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> Pet 306 refactor : 애플 로그인 jwt 라이브러리 변경

- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/oauth/impl/AppleOAuthHandler.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-306 refactor : OIDCToken 반환 형식 수정

- Api-Module/build.gradle
- Batch-Module/build.gradle
- Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/service/WithDrawSaveService.java
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
- 배치 모듈 의존성 설정
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-310 chore : 배치 모듈 의존성 설정

- Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/consts/IgnoredPathConsts.java
- Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/dto/request/LandingRequest.java
- Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/dto/response/UserInfoResponse.java
- Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/mapper/LandingMapper.java
- Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/service/LandingCreateUseCase.java
- Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/Landing.java
- Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/repository/LandingRepository.java
- Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/service/LandingSaveService.java
- Domain-Module/User-Module/User-Presentation/src/main/java/com/pawith/userpresentation/UserController.java
- Domain-Module/User-Module/User-Presentation/src/test/java/com/pawith/userpresentation/UserControllerTest.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-312 랜딩 API 구현

- Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/dto/request/LandingRequest.java
- Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/mapper/LandingMapper.java
- Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/Landing.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-312 refactor : 랜딩 API 요청값 수정

- Common-Module/src/main/java/com/pawith/commonmodule/config/CorsConfig.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-312 feat : CorsConfig 추가

- Domain-Module/Auth-Module/Auth-Presentation/src/main/java/com/pawith/authpresentation/common/security/SecurityConfig.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-312 refactor : SecurityConfig 수정

- Domain-Module/Auth-Module/Auth-Presentation/src/main/java/com/pawith/authpresentation/common/security/SecurityConfig.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> PET-312 refactor : SecurityConfig cors 설정 추가
