TEAM-SAMSION/Backend

Api-Module/src/main/java/com/petmory/apimodule/ApiModuleApplication.java
Auth-Module/JWT/src/main/java/com/petmory/jwt/JWTProvider.java
Auth-Module/auth-adaptor/src/main/java/com/petmory/authmodule/config/security/JWTAuthenticationToken.java
Auth-Module/auth-adaptor/src/main/java/com/petmory/authmodule/config/security/SecurityConfig.java
Auth-Module/auth-adaptor/src/main/java/com/petmory/authmodule/config/security/SecurityHandler.java
Auth-Module/auth-adaptor/src/main/java/com/petmory/authmodule/config/security/filter/JWTAuthenticationFilter.java
Auth-Module/auth-application/build.gradle
Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/common/config/OAuthConfig.java
Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/common/consts/AuthConsts.java
Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/common/consts/IgnoredPathConsts.java
Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/common/exception/AuthException.java
Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/common/exception/InvalidAuthorizationTypeException.java
Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/port/in/JWTExtractEmailUseCase.java
Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/port/in/JWTExtractTokenUseCase.java
Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/port/in/JWTVerifyUseCase.java
Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/service/JWTExtractEmailService.java
Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/service/JWTExtractTokenService.java
Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/service/JWTVerifyService.java
Auth-Module/build.gradle
Common-Module/src/main/java/com/petmory/commonmodule/exception/Error.java

- (auth-adaptor) JWT 인증 필터 및 AuthenticationToken 추가
- (auth-adaptor) Security 설정 및 Security의존성관리 Handler 추가
- (auth-application) Auth Exception 추가
- (auth-application) 토큰 인증, 인증 타입 분리, 이메일 추출 서비스 추가
- (auth-application) OAuthConfig 클래스 위치 변경
- (JWT) access token에서 email 정보 추출 메소드 추가
- refresh token에서 Email 정보 반환 메소드 이름 변경 (extractEmailFromToken -> extractEmailFromRefreshToken)
- 내용을 적어주세요.

Pet 41 feat : JWT 인증 필터 추가 및 JWT 인증, 인증 타입 분리, 이메일 추출 서비스 추가

---

Auth-Module/JWT/src/main/java/com/pawith/jwt/JWTConsts.java
Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/common/config/OAuthConfig.java
Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/common/consts/AuthConsts.java
Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/dto/OAuthResponse.java
Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/factory/DefaultOAuthFactory.java
Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/observer/subject/AbstractOAuthSubject.java
Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/observer/subject/OAuthSubject.java

- 소셜 로그인 결과 OAuthInfo 객체의 email 정보 기반 AccessToken, RefreshToken 생성 후 반환 로직 추가
- AbstractOAuthSubject의 JWTProvider의존성 주입을 위한 initJWTProvider 메소드 추가
- AbstractOAuthSubject 의존성 주입을 위한 메소드 initObserver 메소드에서  initStrategy 메소드로 변경
- AbstractOAuthObserver OAuthObserver 구현체 주입 메소드 initOAuthObserver로 분리
- AbstractOAuthSubject -> OAuthSubject 로 클래스이름 변경
- initObserver -> initStrategy{initOAuthObserver, initJWTProvider}
- 내용을 적어주세요.

PET-69 feat : 소셜 로그인 결과 사용자 email 기반 AccessToken, RefreshToken 생성 로직 추가

---

Api-Module/src/main/java/com/pawith/apimodule/ApiModuleApplication.java
Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/observer/subject/OAuthSubject.java
Common-Module/src/main/java/com/pawith/commonmodule/config/JpaConfig.java
User-Module/user-application/src/main/java/com/pawith/usermodule/application/handler/UserSignUpHandler.java
User-Module/user-domain/src/main/java/com/pawith/usermodule/domain/entity/User.java

- UserRepository 빈등록되지 않는 문제 해결
- OAuthSubject에 ApplicationEventPublisher 빈등록 설정 추가
- EventHandler Component 설정 추가
- User 엔티티 @Entity 애노테이션 추가 및 기본생성자 접근 Protected로 수정
- JpaConfig Common-Module에 추가
- 내용을 적어주세요.
- 내용을 적어주세요.

Pet 72 Fix : ApplicationEventPublisher 빈등록 및 JpaRepository 빈등록 문제 수정

---

Api-Module/src/main/resources/static/docs/Auth-API.html
Auth-Module/auth-adaptor/src/docs/asciidoc/Auth-API.adoc
Auth-Module/auth-adaptor/src/test/java/com/pawith/authmodule/adaptor/api/OAuthControllerTest.java
Auth-Module/auth-adaptor/src/test/java/com/pawith/authmodule/adaptor/api/TestSpringBootApplicationConfig.java
Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/common/consts/IgnoredPathConsts.java
Auth-Module/build.gradle
Common-Module/Test-Module/src/main/java/com/pawith/testmodule/BaseRestDocsTest.java
Common-Module/Test-Module/src/main/java/com/pawith/testmodule/RestDocsConfig.java
build.gradle
settings.gradle

- Rest Docs 설정 추가
- Rest Docs 관련 클래스 관리 Test-Module 추가
- OAuthController 테스트 추가
- Auth-API.adoc 추가
- 내용을 적어주세요.
- 내용을 적어주세요.

Pet 80 chore : RestDocs 설정추가

---

Api-Module/build.gradle
Api-Module/src/docs/asciidoc/Index.adoc
Auth-Module/Auth-Adaptor/src/main/java/com/pawith/authmodule/config/security/JWTAuthenticationToken.java
Auth-Module/Auth-Adaptor/src/test/java/com/pawith/authmodule/adaptor/api/OAuthControllerTest.java
Common-Module/src/main/java/com/pawith/commonmodule/annotation/ApplicationService.java
Common-Module/src/main/java/com/pawith/commonmodule/exception/Error.java
Domain-Module/User-Module/User-Application/src/main/java/com/pawith/usermodule/application/handler/UserSignUpHandler.java
Domain-Module/User-Module/User-Application/src/main/java/com/pawith/usermodule/application/service/UserAuthorityGetUseCase.java
Domain-Module/User-Module/User-Application/src/main/java/com/pawith/usermodule/application/service/dto/UserAuthorityInfoResponse.java
Domain-Module/User-Module/User-Application/src/test/java/com/pawith/user/application/handler/UserSignUpHandlerTest.java
Domain-Module/User-Module/User-Domain/build.gradle
Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/usermodule/domain/entity/Authority.java
Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/usermodule/domain/entity/UserAuthority.java
Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/usermodule/domain/exception/UserAuthorityNotFoundException.java
Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/usermodule/domain/repository/UserAuthorityRepository.java
Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/usermodule/domain/service/UserAuthorityQueryService.java
Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/usermodule/domain/service/UserAuthoritySaveService.java
Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/usermodule/domain/utils/UserUtils.java
Domain-Module/User-Module/User-Presentation/build.gradle
Domain-Module/User-Module/User-Presentation/src/docs/asciidoc/User-API.adoc
Domain-Module/User-Module/User-Presentation/src/main/java/com/pawith/userpresentation/UserAuthorityController.java
Domain-Module/User-Module/User-Presentation/src/test/java/com/pawith/userpresentation/TestSpringBootApplicationConfig.java
Domain-Module/User-Module/User-Presentation/src/test/java/com/pawith/userpresentation/UserAuthorityControllerTest.java

- UserAuthority Domain(Entity, Repository, Service, Exception) 추가
- UserAuthority Application(유저 권한 반환 usecase) 추가
- UserAuthority Presentation(유저 권한 조회 API)추가 및 테스트 추가
- User-API 명세 추가
- Authentication.getPricipal()에서 null 반환하는 문제 수정
- 내용을 적어주세요.
- 내용을 적어주세요.

Pet 89 feat : 사용자 권한 확인 API 추가

---

Auth-Module/Auth-Adaptor/build.gradle
Auth-Module/Auth-Adaptor/src/test/java/com/pawith/authmodule/adaptor/api/OAuthControllerTest.java
Auth-Module/build.gradle
Common-Module/build.gradle
Common-Module/src/main/java/com/pawith/commonmodule/util/SecurityUtils.java
Common-Module/src/testFixtures/java/com/pawith/commonmodule/BaseRestDocsTest.java
Common-Module/src/testFixtures/java/com/pawith/commonmodule/RestDocsConfig.java
Domain-Module/User-Module/User-Application/src/main/java/com/pawith/usermodule/application/service/UserAuthorityGetUseCase.java
Domain-Module/User-Module/User-Domain/build.gradle
Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/usermodule/utils/UserUtils.java
Domain-Module/User-Module/User-Presentation/build.gradle
Domain-Module/User-Module/User-Presentation/src/test/java/com/pawith/userpresentation/UserAuthorityControllerTest.java
build.gradle
gradle/restdocs.gradle
gradle/spring.gradle
gradle/test.gradle
settings.gradle

- Test-Module 제거 후 RestDocs 설정 파일 Common-Module의 testFixture 패키지에서 관리하도록 수정
- UserUtils가 Security 의존성 가지지 않도록 수정
- Common-Module에 SecurityUtils추가
- 내용을 적어주세요.
- 내용을 적어주세요.

Pet 92 refactor : Test-Module 제거 및 testFixture 패키지 추가

---

Auth-Module/Auth-Application/src/test/java/com/pawith/auth/application/JWTExtractEmailServiceTest.java
Auth-Module/Auth-Application/src/test/java/com/pawith/auth/application/JWTExtractTokenServiceTest.java
Auth-Module/Auth-Application/src/test/java/com/pawith/auth/application/JWTVerifyServiceTest.java
Auth-Module/Auth-Application/src/test/java/com/pawith/auth/application/OAuthServiceTest.java
Auth-Module/JWT/src/test/java/com/pawith/jwt/JWTProviderTest.java
Auth-Module/build.gradle
Common-Module/build.gradle
Common-Module/src/main/java/com/pawith/commonmodule/util/SecurityUtils.java
Common-Module/src/testFixtures/java/com/pawith/commonmodule/UnitTestConfig.java
Common-Module/src/testFixtures/java/com/pawith/commonmodule/security/WithMockAuthUser.java
Common-Module/src/testFixtures/java/com/pawith/commonmodule/security/WithMockAuthUserSecurityContextFactory.java
Domain-Module/User-Module/User-Application/src/test/java/com/pawith/usermodule/application/handler/UserSignUpHandlerTest.java
Domain-Module/User-Module/User-Application/src/test/java/com/pawith/usermodule/application/service/UserAuthorityGetUseCaseTest.java
Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/usermodule/domain/entity/UserAuthority.java
Domain-Module/User-Module/User-Domain/src/test/java/com/pawith/usermodule/domain/service/UserAuthorityQueryServiceTest.java
Domain-Module/User-Module/User-Domain/src/test/java/com/pawith/usermodule/domain/service/UserAuthoritySaveServiceTest.java
Domain-Module/User-Module/User-Domain/src/test/java/com/pawith/usermodule/domain/service/UserQueryServiceTest.java
Domain-Module/User-Module/User-Domain/src/test/java/com/pawith/usermodule/domain/service/UserSaveServiceTest.java
Domain-Module/User-Module/User-Presentation/build.gradle
Domain-Module/User-Module/build.gradle
gradle/test.gradle

- UnitTest용 @UnitTestConfig 애노테이션 추가
- 테스트 환경에서 SecurityContextHolder에 사용자 정보 주입 @WithMockAuthUser 애노테이션 추가
- 모든 Unit Test에 @UnitTestConfig 적용
- 테스트 패키지 구조 수정
- 내용을 적어주세요.
- 내용을 적어주세요.

Pet 93 test : Unit Test용 애노테이션 및 테스트 환경에서 SecurityContextHolder에 인증 사용자 정보 주입 애노테이션 추가

---

Auth-Module/Auth-Application/src/main/java/com/pawith/authmodule/application/service/impl/JWTExtractTokenService.java
Auth-Module/Auth-Application/src/main/java/com/pawith/authmodule/common/consts/AuthConsts.java
Auth-Module/Auth-Presentation/src/main/java/com/pawith/authmodule/common/security/filter/JWTAuthenticationFilter.java

- Filter에서 발생하는 예외는 AOP로 잡을 수 없기에 Service에서 예외를 던지도록 수정
- JWTAuthenticationFilter throws InvalidAuthorizationTypeException
-> JWTExtractTokenService throws InvalidAuthorizationTypeException
- 내용을 적어주세요.

PET-101 fix : JWTAuthenticationFilter에서 발생하는 예외 service에서 발생하도록 수정

---

Common-Module/src/main/java/com/pawith/commonmodule/exception/Error.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoProgressResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoRateGetUseCase.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/exception/RegisterNotFoundException.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/CategoryRepository.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoRepository.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/CategoryQueryService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoQueryService.java
Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoHomeController.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoHomeControllerTest.java

- 홈 화면에서 사용될 Todo 달성률 조회 API
- API 테스트 코드 작성, 문서 작성
- 내용을 적어주세요.
- 내용을 적어주세요.

Pet 100 Todo 달성률 조회 API 

---

.gitignore
Api-Module/build.gradle
Domain-Module/Image-Module/Image-Application/src/main/java/com/pawith/imageapplication/service/ImageDeleteUseCase.java
Domain-Module/Image-Module/Image-Application/src/main/java/com/pawith/imageapplication/service/ImageUploadUseCase.java
Domain-Module/Image-Module/Image-Infrastructure/build.gradle
Domain-Module/Image-Module/Image-Infrastructure/src/main/java/com/pawith/imageinfrastructure/config/S3Config.java
Domain-Module/Image-Module/Image-Infrastructure/src/main/java/com/pawith/imageinfrastructure/exception/FileDeleteException.java
Domain-Module/Image-Module/Image-Infrastructure/src/main/java/com/pawith/imageinfrastructure/exception/FileExtentionException.java
Domain-Module/Image-Module/Image-Infrastructure/src/main/java/com/pawith/imageinfrastructure/exception/FileUploadException.java
Domain-Module/Image-Module/Image-Infrastructure/src/main/java/com/pawith/imageinfrastructure/service/S3ImageDeleteUseCaseImpl.java
Domain-Module/Image-Module/Image-Infrastructure/src/main/java/com/pawith/imageinfrastructure/service/S3ImageUploadUseCaseImpl.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoTeamSimpleResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamGetUseCase.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/TodoTeam.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java
Domain-Module/User-Module/User-Application/build.gradle
Domain-Module/User-Module/User-Application/src/main/java/com/pawith/usermodule/dto/request/UserProfileImageUpdateRequest.java
Domain-Module/User-Module/User-Application/src/main/java/com/pawith/usermodule/service/UserProfileImageUpdateUseCase.java
Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/usermodule/entity/User.java
Domain-Module/User-Module/User-Presentation/src/docs/asciidoc/User-API.adoc
Domain-Module/User-Module/User-Presentation/src/main/java/com/pawith/userpresentation/UserController.java
Domain-Module/User-Module/User-Presentation/src/test/java/com/pawith/userpresentation/UserControllerTest.java
Log-Module/Log-Aop/src/main/java/com/pawith/log/aop/LogTrace.java
Log-Module/Log-Aop/src/main/java/com/pawith/log/aop/TraceStatus.java
settings.gradle

- (User-Module)유저 프로필 이미지 수정 API  및 명세 추가
- (Todo-Module) TodoTeam 목록 조회에서 프로필 이미지도 반환되도록 수정
- (Log-Module) ThreadId 공유 문제 수정
- (Image-Module) Image-Applicaion 모듈에 있는 이미지 업로드 구현체 Image-Infrastructure로 이동
- 내용을 적어주세요.
- 내용을 적어주세요.

Pet 99 feat : 유저 프로필 이미지 수정 API 추가

---

Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoCreateUseCase.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Register.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java

- 비동기 방식으로 동작해서 커넥션 풀이 말라버려서 동기 방식으로 수정했습니다.
- Register 엔티티에 userId 필드에 @joincolumn 제거했습니다.
- 비동기 방식으로 동작해서 커넥션 풀이 말라버려서 동기 방식으로 수정했습니다.
- 내용을 적어주세요.

Pet 122 fix : Register 비동기 방식 조회로 인한 Connection Timeout 문제 수정

---

.deploy/nginx/nginx.conf
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/AssignUserInfoResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategorySubTodoResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoListResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/TodoGetUseCaseTest.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignRepository.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignQueryService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/repository/UserRepository.java
Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/service/UserQueryService.java

- Category Id를 통해 Todo 반환 메소드 리팩터링
- DTO 네이밍 변경 ( DTO 이름에 simple 제거해야할것같아 너무 많이 써서 햇갈리네)
- nginx 설정 수정
- AssignQueryService에서 CategoryId와 날짜 기반 검색 메소드 추가
- UserQueryService에서 UserIds 를 통해 key : userId , value : User 맵 반환 메소드 추가
- 내용을 적어주세요.
- 대략 6000개 조회할때 1초정도 시간 걸립니다

Pet 124 refactor : Category Id를 통해 Todo 반환 메소드 리팩터링

---

Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategoryInfoResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategoryListResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterTermResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoListResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/CategoryGetUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/RegistersGetUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/CategoryGetUseCaseTest.java
Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/RegistersGetUseCaseTest.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/CategoryRepository.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/CategoryQueryService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/CategoryQueryServiceTest.java
Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/RegisterQueryServiceTest.java
Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/CategoryController.java
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/CategoryControllerTest.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java

- 투두 리스트 조회 API 리팩터링 
- TodoController의 getTodoList 메서드 PathVariable teamId -> categoryId로 수정
- List 반환 대신 Dto로 감싸서 반환하게 수정, 오타 수정
- API 테스트 코드 수정
- 관련 domain 테스트 코드 작성 (RegisterQueryServiceTest.findUserIdsByCategoryId)
- 투두 리스트 조회를 카테고리 조회 / 투두 + 담당자 조회로 분리하면서 카테고리 조회 API 추가
- 카테고리 조회 API 테스트 코드 작성, 명세 추가 
- 카테고리 조회 관련 application, domain 테스트 코드 작성
- TodoTeam 가입 기간 조회 API 추가, 테스트 코드 작성, 명세 추가
- TodoTeam 가입 기간 조회 관련 application, domain 테스트 코드 작성 
- 내용을 적어주세요.
- 내용을 적어주세요.

Pet 124 refactor : 투두 리스트 조회 API 리팩터링

---

Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/handler/UnusedTokenExpireEventHandler.java
Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/handler/request/UnusedTokenExpireEvent.java
Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/OAuthInvoker.java
Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/command/OAuthInvokerTest.java
Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/repository/TokenRepository.java
Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/service/TokenDeleteService.java
Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/service/TokenQueryService.java
Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/service/impl/TokenDeleteServiceImpl.java
Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/service/impl/TokenQueryServiceImpl.java

- RefreshToken 재발급시 미사용 토큰 삭제 이벤트 메소드 추가
- 내용을 적어주세요.
- 모듈간 이벤트가 아닌 모듈 내부에서 발생하는 이벤트여서 Auth-Application 모듈 내부에 이벤트 클래스 위치했습니다~

Pet 137 feat : RefreshToken 재발급시 미사용 토큰 삭제 이벤트 메소드 추가

---

Common-Module/src/testFixtures/java/com/pawith/commonmodule/utils/FixtureMonkeyUtils.java
Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/consts/AuthConsts.java
Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/consts/IgnoredPathConsts.java
Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/dto/TokenReissueResponse.java
Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/ReissueUseCase.java
Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/OAuthInvoker.java
Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/impl/JWTExtractEmailUseCaseImpl.java
Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/impl/JWTExtractTokenUseCaseImpl.java
Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/impl/JWTVerifyUseCaseImpl.java
Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/impl/LogoutUseCaseImpl.java
Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/impl/OAuthUseCaseImpl.java
Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/impl/ReissueUseCaseImpl.java
Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/LogoutUseCaseImplTest.java
Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/command/OAuthInvokerTest.java
Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/impl/ReissueUseCaseImplTest.java
Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/repository/TokenRepository.java
Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/service/TokenDeleteService.java
Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/service/impl/TokenDeleteServiceImpl.java
Domain-Module/Auth-Module/Auth-Presentation/src/docs/asciidoc/Auth-API.adoc
Domain-Module/Auth-Module/Auth-Presentation/src/main/java/com/pawith/authpresentation/OAuthController.java
Domain-Module/Auth-Module/Auth-Presentation/src/test/java/com/pawith/authpresentation/OAuthControllerTest.java

- 토큰 재발급 API 추가
- 토큰 재발급 API 테스트 및 명세 추가
- FixtureMonkeyUtils에서 자바 기본 타입 String에 관해서 추가 설정했습니다.
- Auth-Application 서비스 클래스들 @Service -> @ApplicationService로 수정
- AuthConsts에 "Bearer " 값을 가지는 AUTHENTICATION_TYPE_PREFIX 추가
- 내용을 적어주세요.
- 내용을 적어주세요.

Pet 126 feat : 토큰 재발급 API 추가

---

.deploy/Dockerfile
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/ManageRegisterInfoResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/ManageRegisterListResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterSimpleInfoResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/TodoTeamMapper.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/ChangeRegisterUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/RegistersGetUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamGetUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/ChangeRegisterUseCaseTest.java
Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/TodoTeamGetUseCaseTest.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Register.java
Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/RegisterController.java
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java

- 팀 코드 조회 API 추가, 명세 추가
- 관리자 페이지 회원 권환 수정 API 추가, 명세 추가
- 관련 application service 테스트 추가
- 가입한 팀원들 조회 API ResponseDto (RegisterSimpleInfoResponse) 추가 정보 필드 추가
- 내용을 적어주세요.

Pet 138 feat : 관리자 페이지 권한 수정 API 추가

---

Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/RegisterController.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java

- url 컨밴션에 맞게 수정
- 내용을 적어주세요.
1. url 시작은 복수형으로하고
2. 세부 조회 (ex: registers/manage/list?teamId=123)의 url형식을 (registers/123/manage)로 설정하기
3. 메소드 이름은 httpMethod+조회내용+세부사항(getRegistersForManage)

Pet 150 refactor : Register API URL 형식 변경

---

Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/CategoryController.java
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/RegisterController.java
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/CategoryControllerTest.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java

- Todo, Register, TodoTeam, Category API Url 수정
- 내용을 적어주세요.
- 내용을 적어주세요.

Pet 151 refactor : Todo, Register, TodoTeam, Category API Url 수정

---

Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategoryInfoListResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategorySubTodoListResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategorySubTodoResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterInfoListResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterInfoResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterManageInfoResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterManageListResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoInfoResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoProgressRateCompareResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoTeamInfoResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoTeamNameResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/TodoTeamMapper.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/CategoryGetUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/RegistersGetUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoRateGetUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamGetUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/CategoryGetUseCaseTest.java
Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/RegistersGetUseCaseTest.java
Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/TodoGetUseCaseTest.java
Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/TodoRateGetUseCaseTest.java
Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/TodoTeamGetUseCaseTest.java
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/CategoryController.java
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/RegisterController.java
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/CategoryControllerTest.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java

- DTO 네이밍 통일성 있고 파악하기 쉽게 수정했습니다.
- 내용을 적어주세요.
1. 엔티티 + 행위 + (Request|Response) 형식
2. 조회의 경우 행위 다음 Info 추가(ex : /teams/{todoTeamId}/register: RegisterInfoResponse)

Pet 155 refactor : DTO 네이밍 수정

---

Common-Module/src/testFixtures/java/com/pawith/commonmodule/utils/FixtureMonkeyUtils.java
Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/feign/response/KakaoUserInfo.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/RegistersGetUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoCreateUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/UnregisterUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/RegistersGetUseCaseTest.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Register.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterSaveService.java
Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/RegisterQueryServiceTest.java
Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/RegisterSaveServiceTest.java
Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/utils/RegisterTestFixtureEntityUtils.java
Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/service/UserQueryService.java

- TodoTeam 탈퇴시 Register 삭제에서 탈퇴 필드 값(isRegistered) 변경하는 방식으로 수정
- Register 엔티티에 탈퇴 필드 값 추가로 검색 메소드에 탈퇴 여부 필터링 메소드 추가
- Register 엔티티에 탈퇴 필드 값 추가로 (탈퇴/비탈퇴) 상태 가지는 테스트 객체 생성 유틸 클래스 추가
- UserQueryService의 findUserMapByIds 메소드 파라미터 함수형 인터페이스에서 userId 리스트 받도록 수정
- UserQueryService의 findUserMapByIds 메소드 파라미터 함수형 인터페이스에서 userId 리스트 받도록 수정에 따른 메소드 및 테스트 수정
- 내용을 적어주세요.

Pet 146 refactor : TodoTeam 탈퇴시 Register 삭제에서 탈퇴 필드 값 변경하는 방식으로 수정

---

Common-Module/src/main/java/com/pawith/commonmodule/event/TodoCompletionCheckEvent.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/AssignUserInfoResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategorySubTodoResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoCompletionResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/TodoCompletionCheckOnTodoHandler.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/event/TodoCompletionCheckEvent.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/AssignChangeUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/handler/TodoCompletionCheckOnTodoHandlerTest.java
Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/AssignChageUseCaseTest.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Assign.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/CompletionStatus.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Todo.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignRepository.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoRepository.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignQueryService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java

- 담당자 Todo 완료 여부 변경 API 추가, 테스트 코드 작성 및 명세 반영
- Todo 최종 완료 여부 변경 이벤트로 구현
- Todo 최종 완료 여부 조회 API 추가, 테스트 코드 작성 및 명세 반영
- 담당자 Todo 완료 여부 필드 추가로 인한 카테고리 하위 Todo 조회 수정, 테스트 코드 반영
- Todo 완료 여부 관련 테스트 코드 작성(AssignChageUseCaseTest, TodoCompletionCheckOnTodoHandler)
- 담당자에 Todo 완료 여부 필드 추가로 인해 TodoStatus Enum 클래스를 CompletionStatus로 네이밍 변경
- 담당자 Todo 완료 여부 필드 추가로 인한 카테고리 하위 Todo 조회 수정
- 내용을 적어주세요.

Pet 152 refactor : Todo 전반적인 로직 수정 

---

Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterManageInfoResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterSearchInfoResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/RegistersGetUseCase.java
Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/RegisterController.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/repository/UserRepository.java
Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/service/UserQueryService.java

- TodoTeam 가입한 사용자 검색 API 추가
- 사용자 조회 응답필드 중 Authority enum으로 반환하도록 수정
- 사용자 조회 API  관리자, 운영진, 멤버 순서대로 정렬해서 반환하도록 수정 
- 내용을 적어주세요.
- 내용을 적어주세요.

Pet 168 feat : TodoTeam 가입한 사용자 검색 API 추가, 사용자 조회 API 수정 

---

Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterTermResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoCountResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/WithdrawAllTodoResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/WithdrawTodoResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/WithdrawTodoTeamResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/CategoryDeleteOnTodoHandler.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/event/CategoryDeleteEvent.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/CategoryDeleteUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamGetUseCase.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignRepository.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoRepository.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoTeamRepository.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignDeleteService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoDeleteService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoQueryService.java
Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java

- TodoTeam 탈퇴, 서비스 탈퇴 시 담당했던 Todo 조회 API 추가, 테스트 코드 작성 및 명세 반영
- TodoTeam 탈퇴, 서비스 탈퇴 시 담당했던 Todo 개수 조회 API 추가, 테스트 코드 작성 및 명세 반영
- Category 삭제 시 관련된 Todo와 Assign 정보 삭제 하도록 변경
- TodoTeam 탈퇴 후, 메인 화면으로 돌아갔을 때 가입한 TodoTeam 리스트에서 해당 TodoTeam은 사라지게 수정
- 내용을 적어주세요.

Pet 170 TodoTeam 탈퇴, 서비스 탈퇴 시 담당했던 Todo 조회 API

---

Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategorySubTodoResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Pet.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignRepository.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/CategoryRepository.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java

- 카테고리 하위 투두 조회 시 사용자가 가장 앞으로 오게 정렬, 해당 투두에 사용자가 할당되어있는지 여부 값 추가 
- 카테고리 하위 투두 조회 시 완료한 투두는 아래로 내려가게 수정 
- 펫 정보 수정 관련 메서드 파라미터 순서 수정
- 내용을 적어주세요.
- 내용을 적어주세요.

Pet 182 refactor : 카테고리 하위 투두 조회 로직 수정, 펫 정보 업데이트 로직 수정 

---

Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategorySubTodoResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoNotificationInfoResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/TodoMapper.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoWithdrawGetUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/TodoGetUseCaseTest.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoNotificationRepository.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoNotificationQueryService.java
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java

- 카테고리 하위 todo 조회시 발생하는 쿼리 최적화 진행
- 카테고리 하위 todo 조회시 알림 설정 여부(접속 사용자 기준) 추가
- 카테고리 하위 todo dto 변환 mapper 메소드 추가
- 패밀리 탈퇴시 사용할 조회 메소드 TodoWithdrawGetUseCase 분리
- 카테고리 하위 todo 조회할때 fetch join으로 todo, register 같이 조회하기에 register 추가 쿼리 제거
- 접속 사용자가 할당된 투두에서 이름 정렬하는 로직 통합하여 불필요한 반복문 제거
- 
- 내용을 적어주세요.

Pet 186 refactor : 카테고리 하위 todo 조회 최적화 및 알림 여부 필드 추가

---

Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/UnregisterUseCase.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterValidateService.java
Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/RegisterController.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/repository/UserRepository.java

- TodoTeam 조회(메인페이지, 투두화면)  정렬 최신순으로 수정
- 닉네임으로 사용자 검색 단어 하나만 입력해도 찾을 수 있게 수정
- TodoTeam 탈퇴 검증 API 분리, 테스트 코드 작성, 명세 반영 
- 서비스 탈퇴 검증 로직 수정 
- 내용을 적어주세요.
- 내용을 적어주세요.

PET-189 refactor : 쿼리 수정, 탈퇴 검증 로직 수정 

---

Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoTeamSearchInfoResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/UserAccountDeleteOnTodoHandler.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/TodoTeamMapper.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/UnregisterUseCase.java
Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/RegisterController.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java

- 팀 코드로 팀 조회 API 응답값에 TeamId 추가, 명세 반영
- 서비스 탈퇴 검증 로직 새로운 API로 분리, 해당 API 테스트 코드 작성, 명세 반영 
- 내용을 적어주세요.
- 내용을 적어주세요.

Pet 194 refactor : 팀 코드로 팀 조회 API 응답값 수정, 서비스 탈퇴 검증 로직 API로 분리 

---

.github/workflows/CD-prod.yml
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/TodoNotificationHandler.java

- 알림 설정 시간과 비교시 스케줄러 시작 시간과 비교하도록 수정
- CD 플로우 이름 수정
- 시간 비교 메소드 제거했습니다.
- 내용을 적어주세요.

Pet 206 fix : 알림 설정 시간과 비교시 스케줄러 시작 시간과 비교하도록 수정

---

Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/TodoNotificationHandler.java

- 알림 데이터 추출시 트랜잭션 범위 조정, 커넥션 점유 시간이 너무 많아서 특정 요청에 대해 응답시간이 느려져 트랜잭션 애노테이션 제거했습니다.
- 내용을 적어주세요.
- 내용을 적어주세요.

PET-230 fix : 알림 데이터 추출시 트랜잭션 범위 조정

---

Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/TodoNotificationHandler.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoNotificationQueryRepository.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/dao/NotificationDao.java
Domain-Module/Todo-Module/Todo-Infrastructure/src/main/java/com/pawith/todoinfrastructure/dao/NotificationDaoImpl.java
Domain-Module/Todo-Module/Todo-Infrastructure/src/main/java/com/pawith/todoinfrastructure/repository/TodoNotificationRepositoryImpl.java

- 알림 조회 쿼리에서 시간 만 비교에서 (할당 날짜 + 설정 시간)으로 비교하여 오전 1,2시에 알림 설정된 경우도 조회할 수 있도록 수정
- LocalTime -> LocalDateTime으로 비교 변경에 따른 파라미터 값 변경
- LocalTime 반환 메소드에서 날짜 포함한 LocalDateTime 반환하도록 수정
- 조회 데이터와 실행 시간과 비교하는 메소드 분리
- 내용을 적어주세요.
- 기존 쿼리에서 시간 기준으로 비교하는데, 이때 23시에 조회 시작하면 (between 23 and 2) 쿼리가 생성되서 다음날 0~2시 사이에 알림 설정은 무시되더라고 그래서 수정했어, (할당 날짜 + 알림 설정 시간)으로

Pet 237 fix : 알림 조회 시 일부 데이터 누락되는 문제 수정

---

Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoCreateUseCase.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterQueryRepository.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
Domain-Module/Todo-Module/Todo-Infrastructure/src/main/java/com/pawith/todoinfrastructure/repository/RegisterRepositoryImpl.java
Event/src/main/java/com/pawith/event/christmas/ChristmasEventListener.java
Event/src/main/java/com/pawith/event/christmas/ChristmasEventService.java

- Register 조회시 todoTeamId가 없으면 categoryId로 조회하도록 수정
- 이벤트 투두는 이벤트 기간이 아니면 생성하지 않도록 수정
- 내용을 적어주세요.
- 내용을 적어주세요.

Pet 275 hotfix : Register 조회시 todoTeamId가 없으면 categoryId로 조회하도록 수정

---

Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoNotificationInfoResponse.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/IncompleteTodoCountNotificationHandler.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/RegistersGetUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoCompleteGetUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/RegistersGetUseCaseTest.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignQueryService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoNotificationQueryService.java
Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/service/UserQueryService.java

- todo 조회 로직 리팩터링
- TodoNotificationInfoResponse record 타입으로 변경 및 인스턴스 생성 메소드 변경
- 내용을 적어주세요.
- todo 조회시 사용한 private 메소드들 각 엔티티에 맞는 QueryService로 옮겼습니다.

Pet 280 refactor : todo 조회 로직 리팩터링

---

Alarm-Module/src/main/java/com/pawith/alarmmodule/exception/AlarmError.java
Common-Module/src/main/java/com/pawith/commonmodule/exception/BusinessException.java
Common-Module/src/main/java/com/pawith/commonmodule/exception/Error.java
Common-Module/src/main/java/com/pawith/commonmodule/exception/GlobalExceptionHandler.java
Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/exception/AuthError.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/IncompleteTodoCountNotificationHandler.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/TodoCompletionCheckOnTodoHandler.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/TodoRemindHandler.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/event/TodoAssignStatusChangeEvent.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/event/TodoCompletionCheckEvent.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/AssignChangeUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/handler/TodoCompletionCheckOnTodoHandlerTest.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/exception/TodoError.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoNotificationQueryService.java
Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/User.java
Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/exception/UserError.java
Image-Module/src/main/java/com/pawith/imagemodule/exception/FileError.java

- 에러코드 인터페이스에 http 상태 코드 조회 추가
- 투두 할당 상태 변경 이벤트 이름 변경
- 미완료 투두가 1개 이상일때만 알림 보내도록 수정
- 내용을 적어주세요.
- 내용을 적어주세요.

Pet 287 feat : 에러코드 인터페이스에 http 상태 코드 조회 추가

---

Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/oauth/impl/AppleOAuthHandler.java

- io.jsonwebtoken.MalformedJwtException해결
- JJWT 라이브러리 버전 변경으로 인해 기존 방식을 사용할 수 없어 kid 값 추출 방식을 변경했습니다
- 내용을 적어주세요.

PET-306 refactor : kid 값 추출 방식 변경, 그에 따른 OIDCToken 파싱 및 반환 형식 수정

---

Batch-Module/src/main/java/com/pawith/batchmodule/todo/IncompleteTodoCountNotificationBatchService.java
Batch-Module/src/main/java/com/pawith/batchmodule/todo/TodoNotificationBatchService.java
Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/service/impl/TokenDeleteServiceImpl.java
Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/AssignChangeUseCase.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignDeleteService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignQueryService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignSaveService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/CategoryDeleteService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/CategoryQueryService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/CategorySaveService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/PetDeleteService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/PetQueryService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/PetSaveService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterDeleteService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterSaveService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterValidateService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoDeleteService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoNotificationQueryService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoNotificationSaveService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoQueryService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoTeamQueryService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoTeamSaveService.java
Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoValidateService.java
Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/service/UserQueryService.java

- 도메인 서비스 내부의 트랜잭션 애노테이션 제거
- 배치 관련 서비스 클래스 배치 모듈로 이동
- 내용을 적어주세요.
- 내용을 적어주세요.

Pet 308 fix : 도메인 서비스 내부의 트랜잭션 애노테이션 제거
